server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.alibaba.cloud.nacos: DEBUG

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      routes:
        - id: helloword
          uri: lb://helloword
          predicates:
            - Path=/hello/**
          filters:
            - StripPrefix=1
